### ISSUE TITLE
latexify form a function defined in an exec will result in OSError

### ISSUE THREAD

**Issue by ontocord** [google/latexify_py#107]
exec("""
def solve(a, b, c):
  return (-b + math.sqrt(b**2 - 4*a*c)) / (2*a)
""")

lat = latexify.get_latex(solve)

Will result in: OSError: could not extract source code

**Comment by odashi** [comment]
I don't think this is easily fixable as the dynamic object doesn't remember its original source.

It may require decompiling the underlying bytecodes into some corresponding source or AST. Since bytecodes lack the original representation of the source code, the result could be distant from the original even if we could restore it.

Maybe the possible workaround is to provide a functionality that takes the source code directly, as in #108 .

**Comment by odashi** [comment]
I will keep this issue opened for a while to gather some ideas.

**Comment by ontocord** [comment]
Yes. I figured that the solution was to go straight from str to latex :)
