### ISSUE TITLE
Сonverting expressions or strings to latex format

### ISSUE THREAD

**Issue by Iashenkovaias** [google/latexify_py#179]
## Сonverting expressions or strings to latex format

Yesterday I discovered your wonderful library and was inspired to use it in my code. However, I encountered the following problem: I work with linear equations and if I write them after return, the function works correctly. For example:
```
@latexify.expression
def find_latex(x):
  expr = -19*(4*x-11)
  return expr
print(str(find_latex))
```
This code works correctly and returns:
```\begin{array}{l} expr = -{19} \left( {4} x - {11} \right) \\ expr \end{array}```

But as soon as I try to take expression from the global environment, I recieve a problem. The code is as follows:
```
expr = -19*(4*x-11)
@latexify.expression
def find_latex(x, expr):
  return expr
print(str(find_latex))
```
Returns: ```expr```

Perhaps I haven’t fully figured out how to use arguments in this function, but I would really like to use this library in my work.
I found issue (https://github.com/google/latexify_py/issues/108), but I also didn’t understand how to use arguments and showed methods to convert string expression to latex (this option is the most suitable for me).

I'am looking forward to your reply!

**Comment by odashi** [comment]
@Iashenkovaias This is currently the expected behavior. `@latexify.expression` can compile only the expressions within the decorated function because it doesn't have ways to know the bound expression of the outer variables. It may require analyzing the whole source around the function, but the current implementation doesn't have such functionality.

Though it is not planned, I think the library may be able to provide some utilities to compile classes or modules with functions and other bound fields.

**Comment by Iashenkovaias** [comment]
@odashi, thank you very much for your answer!
Perhaps you can tell me about your future plans with this library: would you add such functionality to ```latexify``` as reading strings and then generating expression in latex format? In my opinion, such function could be extremely popular :)

**Comment by odashi** [comment]
> Reading strings and then generating expression

It could be provided with some effort. However, Obtaining the "correct" expression of functions that depends on outer variables (I guess this is the topic of this issue) is somewhat not possible because the value of such variables is basically indeterminate.

Example:

```python
c = 42

def f(x):
  return x * c

def change_c(new_c):
  global c
  c = new_c
```

In this case `f(10)` returns 420 if `change_c` has never been invoked, but latexify couldn't determine such semantics by only looking at the def clause. I think this is one of the obvious limitation of this library (and similar tools based on the syntax tree).

**Comment by Iashenkovaias** [comment]
@odashi, once again thank you very much for your answer! I understand you, I’ll try to apply method you described in my project.
Also, I apologize for my lack of understanding features of the library: I recently took up programming more or less seriously, so some aspects are new for me
All the best :)

**Comment by odashi** [comment]
@Iashenkovaias No problem! If you get some ideas to work around this, please re-open the issue and let me know about your thoughts.
