### ISSUE TITLE
Convert output to an image object

### ISSUE THREAD

**Issue by dipeshSam** [google/latexify_py#212]
I want to convert the latex visual output to an image object like PIL Image. Is there any support for this functionality?

Regards.

**Comment by odashi** [comment]
At this point I'm not planning to provide any functionality to tweak LaTeX source, including compiling it to some displaying formats, because it is somewhat out of curiosity of this library.

For single-line outputs, some well-known libraries such as `matplotlib` or `sympy` supports to print LaTeX equations as images. For general documents, LaTeX frontend libraries such as `pylatex` can be used instead.

**Comment by dipeshSam** [comment]
Satisfactory response. Thank you.
