### ISSUE TITLE
support indicies

### ISSUE THREAD

**Issue by MAKMED1337** [google/latexify_py#52]
Add suppot for indicies
```
import math
import latexify

@latexify.with_latex
def solve(a):
	return a[0]

print(solve)
```

to be something like `\mathrm{solve}(a) \triangleq a_0`

**Comment by odashi** [comment]
I considered about some caveats by introducing this. I think there is not so large problem, except we got slices: `a[x:y]`. I also think we can simply raise errors when such input is given.

**Comment by MAKMED1337** [comment]
What to do with a[1][2] ?

**Comment by MAKMED1337** [comment]
> What to do with a[1][2] ?

I think `a_1_2` will be wrong because it's looks like a[12]
maybe `a_{1,2}` or `a_{1\,2}`

**Comment by odashi** [comment]
@MAKMED1337 Ah thanks, your suggestion seems reasonable. It requires some tricky parsing over the syntax tree though: if we found a node chain of indexing, we need to convert it to a single subscript.

Furthermore we might also want some setting to keep the bracket notation as-is: $x[a][b]$ since it is also used frequently.
