### ISSUE TITLE
n+1-1 in sum/prod

### ISSUE THREAD

**Issue by odashi** [google/latexify_py#74]
Currently the analyzer of `sum` and `prod` does not recognize the reducable addition and subtraction in the `stop` parameter of `range`:

<img width="327" src="https://user-images.githubusercontent.com/1023695/199804885-dd54386f-f5e8-477f-a04e-89c45e898796.png">

It would be good if we could get $n$ rather than $n+1-1$ in most cases. This reduction would be safe because [the operands of `range` must be integers](https://docs.python.org/3/library/stdtypes.html#range), whose objects must be always associative and commutative in terms of operations $+$ and $-$.

**Comment by odashi** [comment]
Note that in general arithmetic is not associative even if all operands are numbers. For example:

<img width="442" src="https://user-images.githubusercontent.com/1023695/199812204-e9b7b4e4-5b7d-4929-8a5c-a1cc50e48ae7.png">

So this treatment is available only when the function always takes integers.

**Comment by Casper-Guo** [comment]
Implemented here:

https://github.com/google/latexify_py/blob/c6c291d3bcce28a269d175be384ab955ac2100c8/src/latexify/codegen/function_codegen.py#L335-L354

Current behavior is caused by not being able to convert `n+1` to a numeric type. 

The `n+1` case can perhaps be treated as a special case since it is the most common but a more general solution might be preferred. Since reduction is only needed for `n+x` or `n-x` maybe we can explicitly check for these two cases.

**Comment by odashi** [comment]
@Casper-Guo I think the code above is an obsolete permalink. In the current implementation, FunctionCodegen introduced an additional analyzer that obtains subtree of range:

https://github.com/google/latexify_py/blob/071a12d06ae67c578f92f973945c0067b3f4976d/src/latexify/codegen/function_codegen.py#L334

We can implement the specific process if we detected `range_info.start` is BinOp and the operator is Add or Sub.

**Comment by Casper-Guo** [comment]
We would like to work on this. Can you please assign me and @lakeblair.

**Comment by odashi** [comment]
@Casper-Guo Thanks for taking your effort! Assigned to you anyway since you are the only person who attended this discussion.

**Comment by odashi** [comment]
Resolved by #115
